# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/docs-versioning',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/docs-versioning',
                'lib_path': 'docs_versioning'},
  'syms': {'docs_versioning.core': {'docs_versioning.core.foo': ('core.html#foo', 'docs_versioning/core.py')}}}
