name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/nbdev-mkdocs-ghp@add-support-for-docs-versioning
        with:
          versioned_doc_deployments: true
          doc_version_to_deploy: 0.0.1
